---
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Manifest
metadata:
  name: sample
spec:
  arches:
  - amd64
  operatingSystems:
  - arch: amd64
    type: linux
    id: centos
    version: "7"
    repository:
      iso:
        localPath:
        url: https://github.com/kubesphere/kubekey/releases/download/v3.0.12/centos7-rpms-amd64.iso
  # - arch: amd64
  #   type: linux
  #   id: ubuntu
  #   version: "22.04"
  #   repository:
  #     iso:
  #       localPath:
  #       url: https://github.com/kubesphere/kubekey/releases/download/v3.0.12/ubuntu-22.04-debs-amd64.iso
  kubernetesDistributions:
  - type: kubernetes
    version: v1.28.3
  components:
    helm:
      version: v3.13.1
    cni:
      version: v1.3.0
    etcd:
      version: v3.5.10
    calicoctl:
      version: v3.26.1
   ## For now, if your cluster container runtime is containerd, KubeKey will add a docker 20.10.8 container runtime in the below list.
   ## The reason is KubeKey creates a cluster with containerd by installing a docker first and making kubelet connect the socket file of containerd which docker contained.
    containerRuntimes:
    - type: docker
      version: 24.0.6
    - type: containerd
      version: 1.7.8
    crictl:
      version: v1.28.0
    docker-registry:
      version: "2"
    harbor:
      version: v2.9.1
    docker-compose:
      version: v2.16.0
  images:
  - docker.io/kubesphere/kube-apiserver:v1.28.2
  - docker.io/kubesphere/kube-controller-manager:v1.28.2
  - docker.io/kubesphere/kube-proxy:v1.28.2
  - docker.io/kubesphere/kube-scheduler:v1.28.2
  - docker.io/kubesphere/pause:3.9
  - docker.io/coredns/coredns:1.9.3
  - docker.io/calico/cni:v3.26.1
  - docker.io/calico/kube-controllers:v3.26.1
  - docker.io/calico/node:v3.26.1
  - docker.io/calico/pod2daemon-flexvol:v3.26.1
  - docker.io/calico/typha:v3.26.1
  - docker.io/kubesphere/flannel:v0.12.0
  - docker.io/openebs/provisioner-localpv:3.3.0
  - docker.io/openebs/linux-utils:3.3.0
  - docker.io/library/haproxy:2.3
  - docker.io/kubesphere/nfs-subdir-external-provisioner:v4.0.2
  - docker.io/kubesphere/k8s-dns-node-cache:1.22.20

